apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ait

resources:
  - namespace.yaml
  - configmap.yaml
  - analysis-service/deployment.yaml
  - analysis-service/service.yaml
  - advisory-service/deployment.yaml
  - advisory-service/service.yaml
  - git-proxy/deployment.yaml
  - git-proxy/service.yaml
  - storage-service/deployment.yaml
  - storage-service/service.yaml
  - cell-health/deployment.yaml
  - cell-health/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress/ingress.yaml
