export type InvestmentCategory = 'ipcaPlus' | 'posFixed' | 'prefixed' | 'variable' | 'pension';
export type InvestmentType = 'tesouro' | 'cdb' | 'lci' | 'lca' | 'debenture' | 'cri' | 'cra' | 'fundo' | 'etf' | 'stock' | 'fii' | 'bdr' | 'pgbl' | 'vgbl';
export type Liquidity = 'D+0' | 'D+1' | 'D+2' | 'D+30' | 'D+180' | 'D+360' | 'Vencimento';

export interface Investment {
  id: string;
  name: string;
  category: InvestmentCategory;
  type: InvestmentType;
  subcategory: string;
  typicalReturn: string;
  realReturnEstimate: number;    // estimated annual real return
  riskLevel: 1 | 2 | 3 | 4 | 5;
  liquidity: Liquidity;
  minInvestment: number;         // BRL
  ir: boolean;                   // subject to income tax
  iof: boolean;                  // subject to IOF (usually first 30 days)
  irTable?: 'regressiva' | 'exclusiva' | 'isento';
  where: string[];               // platforms/brokers
  ticker?: string;               // for tradeable assets
  description: string;
  isencaoIR?: boolean;           // special IR exemption (FII dividends, LCI/LCA)
  tags: string[];
}

export const INVESTMENTS: Investment[] = [
  // ─── IPCA+ ────────────────────────────────────────────────────────────────
  {
    id: 'tesouro_ipca_2029',
    name: 'Tesouro IPCA+ 2029',
    category: 'ipcaPlus',
    type: 'tesouro',
    subcategory: 'Título Público',
    typicalReturn: 'IPCA + ~5-6% a.a.',
    realReturnEstimate: 0.055,
    riskLevel: 1,
    liquidity: 'D+1',
    minInvestment: 30,
    ir: true,
    iof: false,
    irTable: 'regressiva',
    where: ['Tesouro Direto'],
    description: 'Título público federal que paga IPCA + taxa prefixada. Ideal para proteção contra inflação no médio prazo.',
    tags: ['ipca', 'inflação', 'governo', 'longo prazo'],
  },
  {
    id: 'tesouro_ipca_2035',
    name: 'Tesouro IPCA+ 2035',
    category: 'ipcaPlus',
    type: 'tesouro',
    subcategory: 'Título Público',
    typicalReturn: 'IPCA + ~5-6% a.a.',
    realReturnEstimate: 0.057,
    riskLevel: 1,
    liquidity: 'D+1',
    minInvestment: 30,
    ir: true,
    iof: false,
    irTable: 'regressiva',
    where: ['Tesouro Direto'],
    description: 'Vencimento mais longo oferece taxa maior. Excelente para o objetivo de R$3M no horizonte de 10-12 anos.',
    tags: ['ipca', 'inflação', 'governo', 'longo prazo'],
  },
  {
    id: 'tesouro_ipca_2045',
    name: 'Tesouro IPCA+ 2045',
    category: 'ipcaPlus',
    type: 'tesouro',
    subcategory: 'Título Público',
    typicalReturn: 'IPCA + ~5-6% a.a.',
    realReturnEstimate: 0.058,
    riskLevel: 1,
    liquidity: 'D+1',
    minInvestment: 30,
    ir: true,
    iof: false,
    irTable: 'regressiva',
    where: ['Tesouro Direto'],
    description: 'Prazo mais longo — maior taxa e maior volatilidade a mercado. Ideal para quem não vai resgatar antes do vencimento.',
    tags: ['ipca', 'inflação', 'governo', 'muito longo prazo'],
  },
  {
    id: 'cdb_ipca',
    name: 'CDB IPCA+',
    category: 'ipcaPlus',
    type: 'cdb',
    subcategory: 'Renda Fixa Bancária',
    typicalReturn: 'IPCA + 4-6% a.a.',
    realReturnEstimate: 0.05,
    riskLevel: 2,
    liquidity: 'Vencimento',
    minInvestment: 1000,
    ir: true,
    iof: true,
    irTable: 'regressiva',
    where: ['XP', 'BTG', 'Rico', 'NuInvest', 'Inter', 'Órama'],
    description: 'Certificado de Depósito Bancário indexado ao IPCA. Coberto pelo FGC até R$250k por CPF por instituição.',
    tags: ['ipca', 'inflação', 'fgc', 'banco'],
  },
  {
    id: 'debentures_ipca',
    name: 'Debêntures IPCA+',
    category: 'ipcaPlus',
    type: 'debenture',
    subcategory: 'Crédito Privado',
    typicalReturn: 'IPCA + 5-8% a.a.',
    realReturnEstimate: 0.065,
    riskLevel: 3,
    liquidity: 'D+2',
    minInvestment: 1000,
    ir: true,
    iof: false,
    irTable: 'regressiva',
    where: ['XP', 'BTG', 'Genial'],
    description: 'Títulos de dívida corporativa. Taxas maiores que Tesouro Direto, com risco de crédito da empresa emissora.',
    tags: ['ipca', 'corporativo', 'crédito privado'],
  },
  {
    id: 'cri_ipca',
    name: 'CRI IPCA+',
    category: 'ipcaPlus',
    type: 'cri',
    subcategory: 'Crédito Imobiliário',
    typicalReturn: 'IPCA + 5-7% a.a.',
    realReturnEstimate: 0.06,
    riskLevel: 3,
    liquidity: 'D+2',
    minInvestment: 1000,
    ir: false,
    iof: false,
    isencaoIR: true,
    where: ['XP', 'BTG', 'Genial', 'Órama'],
    description: 'Certificado de Recebíveis Imobiliários. Isento de IR para pessoa física. Lastro em recebíveis imobiliários.',
    tags: ['ipca', 'imobiliário', 'isento ir', 'crédito privado'],
  },
  {
    id: 'cra_ipca',
    name: 'CRA IPCA+',
    category: 'ipcaPlus',
    type: 'cra',
    subcategory: 'Crédito Agroindustrial',
    typicalReturn: 'IPCA + 5-7% a.a.',
    realReturnEstimate: 0.06,
    riskLevel: 3,
    liquidity: 'D+2',
    minInvestment: 1000,
    ir: false,
    iof: false,
    isencaoIR: true,
    where: ['XP', 'BTG', 'Genial'],
    description: 'Certificado de Recebíveis do Agronegócio. Isento de IR para pessoa física. Lastro em recebíveis do agronegócio.',
    tags: ['ipca', 'agronegócio', 'isento ir', 'crédito privado'],
  },

  // ─── Pós-fixado ──────────────────────────────────────────────────────────
  {
    id: 'tesouro_selic',
    name: 'Tesouro SELIC',
    category: 'posFixed',
    type: 'tesouro',
    subcategory: 'Título Público',
    typicalReturn: '~SELIC a.a. (taxa overnight)',
    realReturnEstimate: 0.02,
    riskLevel: 1,
    liquidity: 'D+1',
    minInvestment: 30,
    ir: true,
    iof: true,
    irTable: 'regressiva',
    where: ['Tesouro Direto'],
    description: 'Título público mais seguro do Brasil. Acompanha a taxa SELIC. Ideal para reserva de emergência e liquidez.',
    tags: ['selic', 'liquidez', 'reserva', 'governo'],
  },
  {
    id: 'cdb_cdi_100',
    name: 'CDB 100% CDI',
    category: 'posFixed',
    type: 'cdb',
    subcategory: 'Renda Fixa Bancária',
    typicalReturn: '100% CDI a.a.',
    realReturnEstimate: 0.015,
    riskLevel: 1,
    liquidity: 'D+0',
    minInvestment: 1,
    ir: true,
    iof: true,
    irTable: 'regressiva',
    where: ['Nubank', 'Inter', 'C6 Bank', 'BTG', 'XP'],
    description: 'CDB com liquidez diária rendendo 100% do CDI. Similar ao Tesouro SELIC. Coberto pelo FGC.',
    tags: ['cdi', 'liquidez', 'fgc', 'banco'],
  },
  {
    id: 'lci_cdi',
    name: 'LCI 90-100% CDI',
    category: 'posFixed',
    type: 'lci',
    subcategory: 'Letra de Crédito',
    typicalReturn: '90-100% CDI (isento IR)',
    realReturnEstimate: 0.02,
    riskLevel: 2,
    liquidity: 'D+30',
    minInvestment: 1000,
    ir: false,
    iof: false,
    isencaoIR: true,
    where: ['XP', 'BTG', 'Rico', 'Banco do Brasil', 'Bradesco'],
    description: 'Letra de Crédito Imobiliário. Isenta de IR para PF. Taxa líquida superior ao CDB com IR.',
    tags: ['cdi', 'isento ir', 'imobiliário', 'fgc'],
  },
  {
    id: 'lca_cdi',
    name: 'LCA 88-95% CDI',
    category: 'posFixed',
    type: 'lca',
    subcategory: 'Letra de Crédito',
    typicalReturn: '88-95% CDI (isento IR)',
    realReturnEstimate: 0.018,
    riskLevel: 2,
    liquidity: 'D+30',
    minInvestment: 1000,
    ir: false,
    iof: false,
    isencaoIR: true,
    where: ['XP', 'BTG', 'Rico', 'Banco do Brasil', 'Bradesco'],
    description: 'Letra de Crédito do Agronegócio. Isenta de IR para PF. Prazo mínimo de carência de 90 dias.',
    tags: ['cdi', 'isento ir', 'agronegócio', 'fgc'],
  },

  // ─── Prefixado ────────────────────────────────────────────────────────────
  {
    id: 'tesouro_prefixado_2027',
    name: 'Tesouro Prefixado 2027',
    category: 'prefixed',
    type: 'tesouro',
    subcategory: 'Título Público',
    typicalReturn: '~13-15% a.a. nominal',
    realReturnEstimate: 0.07,
    riskLevel: 2,
    liquidity: 'D+1',
    minInvestment: 30,
    ir: true,
    iof: false,
    irTable: 'regressiva',
    where: ['Tesouro Direto'],
    description: 'Título público com taxa prefixada. Ideal quando a SELIC está alta e você acredita que vai cair.',
    tags: ['prefixado', 'taxa fixa', 'governo'],
  },
  {
    id: 'cdb_prefixado',
    name: 'CDB Prefixado',
    category: 'prefixed',
    type: 'cdb',
    subcategory: 'Renda Fixa Bancária',
    typicalReturn: '13-17% a.a. nominal',
    realReturnEstimate: 0.065,
    riskLevel: 2,
    liquidity: 'Vencimento',
    minInvestment: 1000,
    ir: true,
    iof: true,
    irTable: 'regressiva',
    where: ['XP', 'BTG', 'Rico', 'NuInvest'],
    description: 'CDB com taxa prefixada. Ganho certo se mantido até vencimento. Bom quando a SELIC está alta.',
    tags: ['prefixado', 'taxa fixa', 'fgc', 'banco'],
  },

  // ─── Renda Variável / Crescimento ────────────────────────────────────────
  {
    id: 'bova11',
    name: 'BOVA11 — ETF Ibovespa',
    category: 'variable',
    type: 'etf',
    subcategory: 'ETF Nacional',
    ticker: 'BOVA11',
    typicalReturn: 'Ibovespa (variável)',
    realReturnEstimate: 0.06,
    riskLevel: 4,
    liquidity: 'D+2',
    minInvestment: 100,
    ir: true,
    iof: false,
    irTable: 'exclusiva',
    where: ['B3 (qualquer corretora)'],
    description: 'ETF que replica o Índice Bovespa. Exposição a ~80 maiores empresas brasileiras. Alta liquidez.',
    tags: ['etf', 'ibovespa', 'ações', 'b3', 'diversificação'],
  },
  {
    id: 'ivvb11',
    name: 'IVVB11 — ETF S&P 500',
    category: 'variable',
    type: 'etf',
    subcategory: 'ETF Internacional',
    ticker: 'IVVB11',
    typicalReturn: 'S&P500 em BRL (variável)',
    realReturnEstimate: 0.08,
    riskLevel: 4,
    liquidity: 'D+2',
    minInvestment: 100,
    ir: true,
    iof: false,
    irTable: 'exclusiva',
    where: ['B3 (qualquer corretora)'],
    description: 'ETF que replica o S&P 500 em reais. Dolarização natural da carteira. Exposição às 500 maiores empresas dos EUA.',
    tags: ['etf', 's&p500', 'internacional', 'dólar', 'diversificação'],
  },
  {
    id: 'hglg11',
    name: 'HGLG11 — FII Logística',
    category: 'variable',
    type: 'fii',
    subcategory: 'Fundo Imobiliário',
    ticker: 'HGLG11',
    typicalReturn: 'DY ~8-10% a.a. + valorização',
    realReturnEstimate: 0.07,
    riskLevel: 3,
    liquidity: 'D+2',
    minInvestment: 100,
    ir: false,
    iof: false,
    isencaoIR: true,
    where: ['B3 (qualquer corretora)'],
    description: 'FII de galpões logísticos. Dividendos mensais isentos de IR para PF. Gestora CSHG.',
    tags: ['fii', 'logística', 'dividendos', 'isento ir', 'imobiliário'],
  },
  {
    id: 'mxrf11',
    name: 'MXRF11 — FII CRI',
    category: 'variable',
    type: 'fii',
    subcategory: 'Fundo Imobiliário',
    ticker: 'MXRF11',
    typicalReturn: 'DY ~10-12% a.a.',
    realReturnEstimate: 0.08,
    riskLevel: 3,
    liquidity: 'D+2',
    minInvestment: 10,
    ir: false,
    iof: false,
    isencaoIR: true,
    where: ['B3 (qualquer corretora)'],
    description: 'FII de papel (CRIs). Dividendos mensais isentos de IR. Gestora Maxi Renda. Ampla base de cotistas.',
    tags: ['fii', 'cri', 'papel', 'dividendos', 'isento ir'],
  },
  {
    id: 'xpml11',
    name: 'XPML11 — FII Shopping',
    category: 'variable',
    type: 'fii',
    subcategory: 'Fundo Imobiliário',
    ticker: 'XPML11',
    typicalReturn: 'DY ~8-9% a.a. + valorização',
    realReturnEstimate: 0.065,
    riskLevel: 3,
    liquidity: 'D+2',
    minInvestment: 100,
    ir: false,
    iof: false,
    isencaoIR: true,
    where: ['B3 (qualquer corretora)'],
    description: 'FII de shoppings. Dividendos mensais isentos de IR. Portfólio de shoppings premium da XP.',
    tags: ['fii', 'shopping', 'dividendos', 'isento ir', 'imobiliário'],
  },
  {
    id: 'petr4',
    name: 'PETR4 — Petrobras PN',
    category: 'variable',
    type: 'stock',
    subcategory: 'Ação',
    ticker: 'PETR4',
    typicalReturn: 'Variável + dividendos',
    realReturnEstimate: 0.08,
    riskLevel: 5,
    liquidity: 'D+2',
    minInvestment: 20,
    ir: true,
    iof: false,
    where: ['B3 (qualquer corretora)'],
    description: 'Ação preferencial da Petrobras. Alta liquidez e dividendos históricos relevantes. Risco político/commodity.',
    tags: ['ação', 'petrobras', 'dividendos', 'commodity', 'b3'],
  },
  {
    id: 'vale3',
    name: 'VALE3 — Vale ON',
    category: 'variable',
    type: 'stock',
    subcategory: 'Ação',
    ticker: 'VALE3',
    typicalReturn: 'Variável + dividendos',
    realReturnEstimate: 0.07,
    riskLevel: 5,
    liquidity: 'D+2',
    minInvestment: 60,
    ir: true,
    iof: false,
    where: ['B3 (qualquer corretora)'],
    description: 'Ação ordinária da Vale. Uma das maiores mineradoras do mundo. Dividendos relevantes. Risco commodity/China.',
    tags: ['ação', 'vale', 'dividendos', 'mineração', 'b3'],
  },

  // ─── Previdência ──────────────────────────────────────────────────────────
  {
    id: 'pgbl',
    name: 'PGBL',
    category: 'pension',
    type: 'pgbl',
    subcategory: 'Previdência Privada',
    typicalReturn: 'Depende do fundo escolhido',
    realReturnEstimate: 0.04,
    riskLevel: 2,
    liquidity: 'D+30',
    minInvestment: 100,
    ir: true,
    iof: false,
    irTable: 'regressiva',
    where: ['Itaú', 'Bradesco', 'Santander', 'BTG', 'XP'],
    description: 'Plano Gerador de Benefício Livre. Dedução de até 12% da renda bruta no IR. Melhor para quem faz declaração completa.',
    tags: ['previdência', 'pgbl', 'dedução ir', 'longo prazo'],
  },
  {
    id: 'vgbl',
    name: 'VGBL',
    category: 'pension',
    type: 'vgbl',
    subcategory: 'Previdência Privada',
    typicalReturn: 'Depende do fundo escolhido',
    realReturnEstimate: 0.04,
    riskLevel: 2,
    liquidity: 'D+30',
    minInvestment: 100,
    ir: true,
    iof: false,
    irTable: 'exclusiva',
    where: ['Itaú', 'Bradesco', 'Santander', 'BTG', 'XP'],
    description: 'Vida Gerador de Benefício Livre. Sem dedução no IR mas IR incide só sobre os rendimentos. Melhor para declaração simplificada.',
    tags: ['previdência', 'vgbl', 'longo prazo', 'sucessão'],
  },
];

export const INVESTMENT_CATEGORIES: Record<InvestmentCategory, { label: string; description: string; color: string }> = {
  ipcaPlus: {
    label: 'IPCA+',
    description: 'Proteção contra inflação — Tesouro IPCA+, CDB IPCA+, CRI, CRA, Debêntures IPCA+',
    color: '#3b82f6',
  },
  posFixed: {
    label: 'Pós-fixado',
    description: 'Liquidez e segurança — Tesouro SELIC, CDB CDI, LCI, LCA',
    color: '#10b981',
  },
  prefixed: {
    label: 'Prefixado',
    description: 'Taxa certa — Tesouro Prefixado, CDB Prefixado',
    color: '#8b5cf6',
  },
  variable: {
    label: 'Renda Variável',
    description: 'Crescimento — ETFs, Ações B3, FIIs, BDRs',
    color: '#f59e0b',
  },
  pension: {
    label: 'Previdência',
    description: 'Aposentadoria + benefícios fiscais — PGBL, VGBL',
    color: '#ec4899',
  },
};
